# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_user_addr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_addr',
            field=models.CharField(max_length=155, null=True),
        ),
    ]
