# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20170905_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_sex',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='MALE', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_specialised',
            field=models.CharField(choices=[('EMPLANT', 'EMPLANT'), ('ORTHO', 'ORTHO')], default='EMPLANT', max_length=15),
        ),
    ]
